server:
  port: 8083
spring:
  application:
    name: "enrollment-service"
  zipkin:
    base-url: http://localhost:9411 #http://zipkin:9411
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    preferIpAddress: false
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/  # http://eurekaserver:8070/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans #http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,shutdown
  endpoint:
    health:
      show-details: always
    shutdown:
      access: unrestricted

logging:
  level:
    org:
      upstarters:
        course: INFO

build:
  version: ${COURSES_VERSION:local}
